/*
February 19th, 2017
Joshua Pickenpaugh
FINAL PROJECT, JAVA 2
 */

/*

Receipt

*/
package final_project_java_02;
 
public class Receipt extends javax.swing.JFrame {

    /**
     * Creates new form Receipt
     */
    public Receipt() {
        initComponents();
        
        //Disables the re-size feature of the JFrame:
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtReceipt01 = new javax.swing.JTextField();
        txtReceipt02 = new javax.swing.JTextField();
        txtReceipt03 = new javax.swing.JTextField();
        txtReceipt04 = new javax.swing.JTextField();
        txtReceipt05 = new javax.swing.JTextField();
        txtReceipt06 = new javax.swing.JTextField();
        txtReceipt07 = new javax.swing.JTextField();
        txtReceipt08 = new javax.swing.JTextField();
        txtReceipt09 = new javax.swing.JTextField();
        txtReceipt10 = new javax.swing.JTextField();
        txtReceipt11 = new javax.swing.JTextField();
        txtReceipt12 = new javax.swing.JTextField();
        txtReceipt13 = new javax.swing.JTextField();
        txtReceipt14 = new javax.swing.JTextField();
        txtTOTAL = new javax.swing.JTextField();
        txtShipping = new javax.swing.JTextField();
        txtSalesTax = new javax.swing.JTextField();
        txtSubTotal = new javax.swing.JTextField();
        btnSendOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtReceipt01.setEditable(false);
        txtReceipt01.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtReceipt02.setEditable(false);
        txtReceipt02.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtReceipt03.setEditable(false);
        txtReceipt03.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtReceipt04.setEditable(false);
        txtReceipt04.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtReceipt05.setEditable(false);
        txtReceipt05.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtReceipt06.setEditable(false);
        txtReceipt06.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtReceipt07.setEditable(false);
        txtReceipt07.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtReceipt08.setEditable(false);
        txtReceipt08.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtReceipt09.setEditable(false);
        txtReceipt09.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtReceipt10.setEditable(false);
        txtReceipt10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtReceipt11.setEditable(false);
        txtReceipt11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtReceipt12.setEditable(false);
        txtReceipt12.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtReceipt13.setEditable(false);
        txtReceipt13.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtReceipt14.setEditable(false);
        txtReceipt14.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtTOTAL.setEditable(false);
        txtTOTAL.setBackground(new java.awt.Color(240, 240, 100));
        txtTOTAL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTOTAL.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtShipping.setEditable(false);
        txtShipping.setBackground(new java.awt.Color(200, 200, 200));
        txtShipping.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txtShipping.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtSalesTax.setEditable(false);
        txtSalesTax.setBackground(new java.awt.Color(200, 200, 200));
        txtSalesTax.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txtSalesTax.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtSubTotal.setBackground(new java.awt.Color(200, 200, 200));
        txtSubTotal.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txtSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnSendOrder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSendOrder.setText("SEND ORDER");
        btnSendOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtReceipt01)
                    .addComponent(txtReceipt02)
                    .addComponent(txtReceipt03)
                    .addComponent(txtReceipt04)
                    .addComponent(txtReceipt05)
                    .addComponent(txtReceipt06)
                    .addComponent(txtReceipt07)
                    .addComponent(txtReceipt08)
                    .addComponent(txtReceipt09)
                    .addComponent(txtReceipt10)
                    .addComponent(txtReceipt11)
                    .addComponent(txtReceipt12)
                    .addComponent(txtReceipt13)
                    .addComponent(txtReceipt14)
                    .addComponent(txtTOTAL, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtShipping)
                    .addComponent(txtSalesTax)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(btnSendOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtReceipt01, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReceipt02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReceipt03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReceipt04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReceipt05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReceipt06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReceipt07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReceipt08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReceipt09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReceipt10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReceipt11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReceipt12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReceipt13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReceipt14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSalesTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtShipping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSendOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Closes the application (later, would actually send the data to server):
    private void btnSendOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendOrderActionPerformed
        
         System.exit(0);
    }//GEN-LAST:event_btnSendOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt().setVisible(true);
            }
        });
    }
    
    public void SetTextBox01(String strItem)
    {
        txtReceipt01.setText(strItem);
    }
    public void SetTextBox02(String strItem)
    {
        txtReceipt02.setText(strItem);
    }
    public void SetTextBox03(String strItem)
    {
        txtReceipt03.setText(strItem);
    }
    public void SetTextBox04(String strItem)
    {
        txtReceipt04.setText(strItem);
    }
    public void SetTextBox05(String strItem)
    {
        txtReceipt05.setText(strItem);
    }
    public void SetTextBox06(String strItem)
    {
        txtReceipt06.setText(strItem);
    }
    public void SetTextBox07(String strItem)
    {
        txtReceipt07.setText(strItem);
    }
    public void SetTextBox08(String strItem)
    {
        txtReceipt08.setText(strItem);
    }
    public void SetTextBox09(String strItem)
    {
        txtReceipt09.setText(strItem);
    }
    public void SetTextBox10(String strItem)
    {
        txtReceipt10.setText(strItem);
    }
    public void SetTextBox11(String strItem)
    {
        txtReceipt11.setText(strItem);
    }
    public void SetTextBox12(String strItem)
    {
        txtReceipt12.setText(strItem);
    }
    public void SetTextBox13(String strItem)
    {
        txtReceipt13.setText(strItem);
    }
    public void SetTextBox14(String strItem)
    {
        txtReceipt14.setText(strItem);
    }
    public void SetSubTotalTextBox(String strItem)
    {
        txtSubTotal.setText("Subtotal: " + strItem);
    }
    public void SetSalesTaxTextBox(String strItem)
    {
        txtSalesTax.setText("Sales Tax: " + strItem);
    }
    public void SetShippingChargeTextBox(String strItem)
    {
        txtShipping.setText("Shipping: " + strItem);
    }
    public void SetTOTALTextBox(String strItem)
    {
        txtTOTAL.setText(strItem);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendOrder;
    private javax.swing.JTextField txtReceipt01;
    private javax.swing.JTextField txtReceipt02;
    private javax.swing.JTextField txtReceipt03;
    private javax.swing.JTextField txtReceipt04;
    private javax.swing.JTextField txtReceipt05;
    private javax.swing.JTextField txtReceipt06;
    private javax.swing.JTextField txtReceipt07;
    private javax.swing.JTextField txtReceipt08;
    private javax.swing.JTextField txtReceipt09;
    private javax.swing.JTextField txtReceipt10;
    private javax.swing.JTextField txtReceipt11;
    private javax.swing.JTextField txtReceipt12;
    private javax.swing.JTextField txtReceipt13;
    private javax.swing.JTextField txtReceipt14;
    private javax.swing.JTextField txtSalesTax;
    private javax.swing.JTextField txtShipping;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTOTAL;
    // End of variables declaration//GEN-END:variables
}
